apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: spr-sample-multi-terms
spec:
  title: This is Sample Course Lab with Multiple Terminals
  description: "Multiple Terminals, fun!"
  duration: "60m"
  workshop:
    image: jdk17-environment:*
    packages:
      - name: spring-academy-lab
        files:
          - image:
              url:
                ghcr.io/spring-academy/spring-academy-extension-packages/spring-academy-lab
              tagSelection:
                semver:
                  constraints: ">=1.0.0 <2.0.0"
    files:
      - http:
          url: "$(ingress_protocol)://$(assets_repository)/$(workshop_name).tar.gz"
        includePaths:
          - /workshop/**
      - path: .local/share/code-server
        image:
          url: ghcr.io/spring-academy/vscode-java-tools-$(platform_arch)-files:0.25.14
      - path: exercises
        git:
          url: https://github.com/spring-academy/course-spring-academy-sample-code
          ref: main
        newRootPath: .
  request:
    parameters:
    - name: USER_DOMAIN
      value: "unknown.domain"
    - name: USER_EMAIL
      value: "somebody@unknown.domain"
  session:
    env:
      - name: LAB_VERSION
        value: "${VERSION}"
      - name: WEBSERVER
        value: "$(ingress_protocol)://$(assets_repository)"
    namespaces:
      budget: medium
      security:
        policy: baseline
        rules:
          exclude:
            - no-localhost-service
            - restrict-nodeport
    resources:
      memory: 2Gi
    ingresses:
      - name: webapp-public
        port: 8080
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
  environment:
    assets:
      memory: 0Mi
      ingress:
        enabled: true
      files:
        - image:
            url: ${CONTAINER_REGISTRY}${CONTAINER_REPOSITORY}:${VERSION}
          newRootPath: usr/share/nginx/html
